# 서버 포트 설정
server:
  port: 9090
  file:
    base-path-mac: /files/upload/  # /files/upload/ 는 고정하기. 앞에 /Users/username 만 변경할 것.
    menu:
      path: C:\files\upload\menu\
    store:
      path: C:\files\upload\store\
    review:
      path: C:\files\upload\review\
      
  # 인코딩 설정
  servlet:
    encoding:
      charset: 'UTF-8'
      enabled: true
      force: true
      force-request: true
      force_response: true

spring:
  main:
    allow-bean-definition-overriding: true  # bean 메소드 오버라이딩 허용할 것인지
  jwt:
    secretKey: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb  # 암호화 할 때 사용할 JWT 시크릿 키
  application:
    name: app-bmpc

  # Database 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://aws-db.cqriy8i04482.us-east-1.rds.amazonaws.com:3306/bmpc_db
    username: root
    password: jude0098
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 50
      minimum-idle: 20
      idle-timeout: 10000
      data-source-properties:
        cachePrepStmts: true # 캐쉬 설정 on
        prepStmtCacheSize: 250 # 문서 할당 수
        prepStmtCacheSqlLimit: 2048 # sql 최대 길이 byte 단위
        useServerPrepStmts: true # 최신기능 지원 설정 on

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    database: mysql
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
        use_sql_comments: false
        cache:
          use_second_level_cache: false
          use_query_cache: false

  # thymeleaf 설정 > jstl 대용품
  thymeleaf:
    cache: false
    check-template-location: true
    encoding: utf-8
    servlet:
      content-type: text/html
    prefix:
      file:src/main/resources/templates/ # 개발버전, 배포버전은 다르게 써야함.
      # prefix: classpath:templates/
    suffix: .html

  # 코드 수정 시 자동으로 컴파일 & 적용
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
    restart:
      enabled: true

# 로그 설정
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO
      thymeleaf: OFF
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
  config: classpath:logback.xml

# SMS 발송 API 설정
coolsms:
  api:
    key: NCSQVL1KBTAIBVIY
    secret: KUSZJIWNCPW69MBQMOQSDPU36XRINQXQ
    number: 01055283638

# Swagger 세팅
springdoc:
  swagger-ui:
    path: /swagger
    persist-authorization: true  # 토큰 값 유지 여부
    filter: true
    try-it-out-enabled: false
  paths-to-match: /api/**  # /api 로 시작하는 것들만 가져오겠다는 뜻
  api-docs:
    path: /v3/api-docs